name: build release
run-name: ${{ github.actor }} runs a release build
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  it_build:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        include:
          - os: ubuntu-20.04
            target: linux
          - os: macos-latest
            target: darwin
    steps:
      - uses: actions/checkout@v3
      - name: Print gcc version
        run: gcc --version
      - name: Install GTK 3 (apt-get)
        if: ${{ matrix.target == 'linux' }}
        run: sudo apt-get install libgtk-3-dev libsystemd-dev
      - name: Install GTK 3 (brew)
        if: ${{ matrix.target == 'darwin' }}
        run: brew install gtk+3
      - name: Make all
        run: make
      - name: Archive it-${{ matrix.target }}.zip
        run: zip it-${{ matrix.target }}.zip it
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: it-${{ matrix.target }}.zip
          asset_name: it-${{ matrix.target }}.zip
          asset_content_type: application/zip
